version: "3"
services:
  mongo:
    ports:
      - 27017:27017
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
